### ISSUE TITLE
Split Zsh's configuration files

### ISSUE THREAD

**Issue by toshiki-rlearning** [toshiki670/dotfiles#11]
### ログインシェルとして zsh が起動された場合
- ~/.zshenv
- ~/.zprofile
- ~/.zshrc
- ~/.zlogin
### インタラクティブシェルとして zsh が起動された場合
- ~/.zshenv
- ~/.zshrc
### シェルスクリプトを実行するコマンドとして zsh が起動された場合
- ~/.zshenv
### ログインシェルとして起動された zsh からログアウトする場合
- ~/.zlogout

**Comment by toshiki670** [comment]
https://wiki.archlinux.jp/index.php/Pkgfile#.22Command_not_found.22_.E3.83.95.E3.83.83.E3.82.AF

`source /usr/share/doc/pkgfile/command-not-found.zsh`
