### ISSUE TITLE
Create installer.sh

### ISSUE THREAD

**Issue by toshiki-rlearning** [toshiki670/dotfiles#5]
# インストーラ作成
## 準備
* vim, zsh ともに前提となるプログラムやプラグインを纏める
* Shellスクリプトを学習
 - ファイルの有無をIFで確認
 - 文字列の結合などの操作を学習

## 完成形
* installerを実行してすぐに環境が完成すること

## 注意点
* 既存環境のファイルを削除などのクリティカルな操作を行わないこと
 - シンボリックファイルを作成した際、元ファイルの削除など

## 検討
* vim のプラグインをDotfilesに入れるか、公式通りに.cacheに保存するか検討

**Comment by toshiki670** [comment]
- InstallerにGitの設定を追加
- 既存のDotfilesを退避する処理を追加

**Comment by toshiki670** [comment]
いつの間にか目的を達成していたためClose
